// web/lib/course/skins.ts — course data: themed world skins (display, mentor, companion, decoder).
// Cross-consumed by workers/ (via lib/rpg/skins-meta re-export), so imports MUST be relative
// (NOT the @/ alias — workers tsc can't resolve it; Gotcha 2). Engine helpers live in
// lib/rpg/skins-meta.ts and read SKINS_META from here.
import type { SkinMeta, WorldSkin } from '../rpg/types'

export const SKINS_META: Record<WorldSkin, SkinMeta> = {
  'slavic-myth':   { skin: 'slavic-myth',   accent: '#7bd88f', glyph: '🌿', displayName: { ru: 'Славянский Миф', en: 'Slavic Myth' }, mentor: { name: { ru: 'Домовой', en: 'House-Spirit' }, glyph: '🪆' }, companion: { name: { ru: 'Котофей', en: 'Kotofey' }, glyph: '🐈‍⬛', vibe: { ru: 'кот-баюн, что вынюхивает каждую тропу', en: 'a cat-spirit who sniffs out every path' } }, decoder: { ru: 'Твой мир — Славянский Миф: уроки звучат как сказ, наставник — Домовой, агенты — помощники у очага. Это лишь образ — под ним обычный курс.', en: "Your world is Slavic Myth: lessons sound like folk tales, your mentor is the House-Spirit, agents are hearth-helpers. It's just imagery — underneath is a normal course." } },
  'dark-fantasy':  { skin: 'dark-fantasy',  accent: '#ff5577', glyph: '🏰', displayName: { ru: 'Тёмное Фэнтези', en: 'Dark Fantasy' }, mentor: { name: { ru: 'Хранитель', en: 'The Keeper' }, glyph: '🗝️' }, companion: { name: { ru: 'Импи', en: 'Impy' }, glyph: '🦇', vibe: { ru: 'мелкий бес на побегушках, тащит находки', en: 'a little imp on errands, dragging back finds' } }, decoder: { ru: 'Твой мир — Тёмное Фэнтези: модули — Искажённые Земли, навыки — Печати, наставник — Хранитель. Это лишь антураж — под ним обычный курс.', en: "Your world is Dark Fantasy: modules are Blighted Lands, skills are Seals, your mentor is the Keeper. It's just set dressing — underneath is a normal course." } },
  'cyber-noir':    { skin: 'cyber-noir',    accent: '#00e5ff', glyph: '🕶️', displayName: { ru: 'Кибер-Нуар', en: 'Cyber Noir' }, mentor: { name: { ru: 'Фиксер', en: 'The Fixer' }, glyph: '🕶️' }, companion: { name: { ru: 'Глитч', en: 'Glitch' }, glyph: '👾', vibe: { ru: 'дрон-разведчик, любопытный до багов', en: 'a recon drone, curious about every bug' } }, decoder: { ru: 'Твой мир — Кибер-Нуар: локации — притоны и мастерские, наставник — Фиксер. Это лишь стиль — под ним обычный курс.', en: "Your world is Cyber Noir: locations are dens and workshops, your mentor is the Fixer. It's just style — underneath is a normal course." } },
  'space-opera':   { skin: 'space-opera',   accent: '#4d8cff', glyph: '🚀', displayName: { ru: 'Космическая Опера', en: 'Space Opera' }, mentor: { name: { ru: 'Бортовой ИИ', en: 'Ship AI' }, glyph: '🛰️' }, companion: { name: { ru: 'Тачикома', en: 'Tachikoma' }, glyph: '🕷️', vibe: { ru: 'любопытный think-tank, болтает и учится на ходу', en: 'a curious think-tank, chattering and learning as it goes' } }, decoder: { ru: 'Твой мир — Космическая Опера: тебя зовут кадетом, задания — миссии, ошибки — аномалии, наставник — Бортовой ИИ. Это лишь декорация — под ней обычный курс.', en: "Your world is Space Opera: you're the cadet, tasks are missions, mistakes are anomalies, your mentor is the Ship AI. It's just decoration — underneath is a normal course." } },
  'anime-quest':   { skin: 'anime-quest',   accent: '#ff7ace', glyph: '🎌', displayName: { ru: 'Аниме-Квест', en: 'Anime Quest' }, mentor: { name: { ru: 'Сэнсэй', en: 'Sensei' }, glyph: '🥋' }, companion: { name: { ru: 'Тама', en: 'Tama' }, glyph: '🐾', vibe: { ru: 'задорный маскот, подбадривает в бою', en: 'a peppy mascot cheering you through battles' } }, decoder: { ru: 'Твой мир — Аниме-Квест: уроки — арки и битвы, наставник — Сэнсэй. Это лишь подача — под ней обычный курс.', en: "Your world is Anime Quest: lessons are arcs and battles, your mentor is the Sensei. It's just presentation — underneath is a normal course." } },
  'soviet-heroic': { skin: 'soviet-heroic', accent: '#e0b020', glyph: '🏛', displayName: { ru: 'Советский Героизм', en: 'Soviet Heroic' }, mentor: { name: { ru: 'Бригадир', en: 'The Foreman' }, glyph: '🔧' }, companion: { name: { ru: 'Винтик', en: 'Vintik' }, glyph: '⚙️', vibe: { ru: 'робот-трудяга, чинит и подаёт инструмент', en: 'a worker-bot, fixing and handing you tools' } }, decoder: { ru: 'Твой мир — Советский Героизм: курс — производственный план, наставник — Бригадир. Это лишь стилистика — под ней обычный курс.', en: "Your world is Soviet Heroic: the course is a production plan, your mentor is the Foreman. It's just styling — underneath is a normal course." } },
  'mystic-arcane': { skin: 'mystic-arcane', accent: '#b388ff', glyph: '🔮', displayName: { ru: 'Мистическая Аркана', en: 'Mystic Arcane' }, mentor: { name: { ru: 'Оракул', en: 'The Oracle' }, glyph: '🔮' }, companion: { name: { ru: 'Совёнок', en: 'Owlet' }, glyph: '🦉', vibe: { ru: 'фамильяр-совёнок, шепчет подсказки', en: 'an owlet familiar whispering hints' } }, decoder: { ru: 'Твой мир — Мистическая Аркана: навыки — руны и заклинания, наставник — Оракул. Это лишь образность — под ней обычный курс.', en: "Your world is Mystic Arcane: skills are runes and spells, your mentor is the Oracle. It's just imagery — underneath is a normal course." } },
  'wanderer':      { skin: 'wanderer',      accent: '#00d1ff', glyph: '🌀', displayName: { ru: 'Странник', en: 'Wanderer' }, mentor: { name: { ru: 'Проводник', en: 'Guide' }, glyph: '🧭' }, companion: { name: { ru: 'Огонёк', en: 'Wisp' }, glyph: '✨', vibe: { ru: 'тихий огонёк, что светит на шаг вперёд', en: 'a quiet wisp lighting one step ahead' } }, decoder: { ru: 'Твой мир — Странник: спокойный нейтральный стиль, наставник — Проводник. Под ним — обычный курс, без лишней мишуры.', en: "Your world is Wanderer: a calm, neutral style, your mentor is the Guide. Underneath is a normal course, with no extra frills." } },
}
