import type { MetadataRoute } from 'next'

// Static-exported to /manifest.webmanifest at build (output: 'export').
// force-static is required for metadata routes under output: 'export'.
export const dynamic = 'force-static'

// Icons live in public/ (generated by scripts/gen-pwa-icons.mjs from app/icon.svg).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Точка Сборки — курс по vibe-кодингу',
    short_name: 'Точка Сборки',
    description: 'Открытый курс по AI-разработке и агентному программированию.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    lang: 'ru',
    dir: 'ltr',
    categories: ['education'],
    theme_color: '#0a0a0f',
    background_color: '#0a0a0f',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }
}
